Muttype heatmap, facets germ thresh, pyvcf version
jrflab/modules pull request #217
Opened 2016-10-03 18:29 UTC by inodb

These changes were driven by Tari King's cfDNA project:

- Add germline threshold for SNPs. Without it the cfDNA/tumor samples wouldn't
  match.
- Add same threshold for Facets
- Different pyvcf version, does not have `source=` option in function call
- Add mutation type heatmap that has the same gene/sample ordering as the ccf
  heatmap. Based on @hxrts Pascal heatmap

2016-10-05 17:58 UTC, raylim requested changes

2016-10-05 17:58 UTC, raylim commented on summary/mutationSummary.mk
> +>>>>>>> Stashed changes
oops

2016-10-05 17:58 UTC, raylim commented on vcf_tools/annotateSomaticVcf.mk
> +>>>>>>> Stashed changes
oops

2016-10-25 18:46 UTC, inodb commented
Fixed in #224

2016-10-25 18:46 UTC, closed without merging